name: shelf_sse
version: 0.0.1
description: A shelf handler that wires up a listener for every connection.
repository: https://github.com/jamiewest/shelf_sse

topics:
  - server
  - shelf

environment:
  sdk: ^3.9.2

dependencies:
  shelf: ^1.4.2
  stream_channel: ^2.1.0
  sse_channel: ^0.2.1

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  http: '>=0.13.0 <2.0.0'
  test: ^1.25.2